columns_eng = {
    "País": "Country",
    "Cidade/Região": "City/region",
    "Período": "Period",
    "Anfitrião": "Host",
    "Notas": "Overview",

}
year_col = "year"
data_visit_columns = list(columns_eng.values())
data_visit_columns.append(year_col)

country_mapping = {
    "Angola" : "Angola",
    "Alemanha": "Germany",
    "Andorra": "Andorra",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Austria": "Austria",
    "Austrália": "Australia",
    "Azerbaijão": "Azerbaijan",
    "Bélgica": "Belgium",
    "Bolívia": "Bolivia",
    "Bósnia e Herzegovina": "Bosnia and Herzegovina",
    "Brasil": "Brazil",
    "Bulgária": "Bulgaria",
    "Canadá": "Canada",
    "Chile": "Chile",
    "China": "China",
    "Catar": "Qatar",
    "Colômbia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Croácia": "Croatia",
    "Cuba": "Cuba",
    "Dinamarca": "Denmark",
    "Equador": "Ecuador",
    "Eslováquia": "Slovakia",
    "Eslovênia": "Slovenia",
    "Espanha": "Spain",
    "Estados Unidos": "United States of America",
    "EUA": "United States of America",
    "Estônia": "Estonia",
    "Etiópia": "Ethiopia",
    "Finlândia": "Finland",
    "França": "France",
    "Geórgia": "Georgia",
    "Grécia": "Greece",
    "Guatemala": "Guatemala",
    "Guiana": "Guyana",
    "Honduras": "Honduras",
    "Hungria": "Hungary",
    "Haiti": "Haiti",
    "Islândia": "Iceland",
    "Índia": "India",
    "Japão": "Japan",
    "Cabo Verde": "Cape Verde",
    "África do Sul": "South Africa",
    "Irlanda": "Ireland",
    "Itália": "Italy",
    "Inglaterra": "United Kingdom",
    "Latvia": "Latvia",
    "Liechtenstein": "Liechtenstein",
    "Lituânia": "Lithuania",
    "Luxemburgo": "Luxembourg",
    "Macedônia": "Macedonia",
    "Malta": "Malta",
    "México": "Mexico",
    "Moldova": "Moldova",
    "Mônaco": "Monaco",
    "Montenegro": "Montenegro",
    "Países Baixos": "Netherlands",
    "Nicarágua": "Nicaragua",
    "Noruega": "Norway",
    "Panamá": "Panama",
    "Paraguai": "Paraguay",
    "Peru": "Peru",
    "Polônia": "Poland",
    "Portugal": "Portugal",
    "Reino Unido": "United Kingdom",
    "República Checa": "Czech Republic",
    "Romênia": "Romania",
    "Rússia": "Russia",
    "San Marino": "San Marino",
    "Sérvia": "Serbia",
    "Sérvia e Montenegro": "Serbia and Montenegro",
    "Suécia": "Sweden",
    "Suíça": "Switzerland",
    "Suriname": "Suriname",
    "Turquia": "Turkey",
    "Ucrânia": "Ukraine",
    "Uruguai": "Uruguay",
    "Venezuela": "Venezuela",
    "Guiné Equatorial": "Equatorial Guinea",
    "Nigéria": "Nigeria",
    "Moçambique": "Mozambique"
}

city_mapping = {
    "Moscou": "Moscow",
    "Oslo": "Oslo",
    "Hamburgo": "Hamburg",
    "Mendoza": "Mendoza",
    "Lisboa": "Lisbon",
    "Pequim": "Beijing",
    "Xiamen": "Xiamen",
    "Nova York": "New York",
    "Buenos Aires": "Buenos Aires",
    "Zurique": "Zurich",
    "Vinã del Mar": "Viña del Mar",
    "Lima": "Lima",
    "Assunção": "Asunción",
    'Ilha do Sal': "Sal",
    "Puerto Vallarta": "Puerto Vallarta",
    "Joanesburgo": "Johannesburg",
    "Quito": "Quito",
    "Santiago": "Santiago",
    "Nova Iorque": "New York",
    "La Paz": "La Paz",
    "San José": "San Jose",
    "Colônia": "Colonia del Sacramento",
    "Montevidéu": "Montevideo",
    "Cidade do Panamá": "Panama City",
    "Cidade do México": "Mexico City",
    "Bruxelas": "Brussels",
    "Washington": "Washington",
    "São Francisco": "San Francisco",
    "Ufa": "Ufa",
    "Roma e Milão": "Rome and Milan",
    "Roma": "Rome",
    "Milão": "Milan",
    "Bogotá": "Bogota",
    "Estocolmo": "Stockholm",
    "Linköping": "Linköping",
    "Helsinque": "Helsinki ",
    "Antália": "Antalya",
    "Paris": "Paris",
    "Malabo": "Malabo",
    "Abuja": "Abuja",
    "Caracas": "Caracas",
    "Durban": "Durban",
    "Adis Abeba": "Adis Abeba",
    "Paramaribo": "Paramaribo",
    "Petersburgo": "Saint Petersburg",
    "Joanesbugo": "Johannesburg",
    "Davos": "Davos",
    "Província de Artemisa": "Artemisa Province",
    "Havana": "Havana",
    "Valparaiso": "Valparaiso",
    "Doha": "Doha",
    "Brisbane": "Brisbane",
    "Província de Entre Rios": "Entre Rios Province",
    "Porto Príncipe": "Port-au-Prince",
    "Hannover": "Hanover",
    "Nova Délhi": "New Delhi",
    "Boston": "Boston",
    "Cartagena das Índias": "Cartagena ",
    "Los Cabos": "Los Cabos",
    "Londres": "London",
    "Cadiz": "Cadiz",
    "Sevilha": "Seville",
    "Madri": "Madrid",
    "Lisboa e Coimbra": "Lisbon and Coimbra",
    "Sanya": "Sanya",
    "Boao": "Boao",
    "Xian": "Xian",
    "Sófia": "Sofia",
    "Gorna Oryahovitsa": "Gorna Oryahovitsa",
    "Ancara": "Ankara",
    "Pretória": "Pretoria",
    "Maputo": "Maputo",
    "Luanda": "Luanda",
    "Cannes": "Cannes",
    "Pequim, Sanya, Boao e Xian": "Pequim, Sanya, Boao e Xian"
}
