columns_eng = {
    "País": "Country",
    "Cidade/Região": "City/region",
    "Período": "Period",
    "Anfitrião": "Host",
    "Notas": "Overview",

}
year_col = "year"
data_visit_columns = list(columns_eng.values())
data_visit_columns.append(year_col)

capital = "---capital"
entity = "---entity"

country_mapping = {
    "Argélia": "Algeria",
    "Ecowas": "Economic Community of West African States",
    "do Japão": "Japan",
    "Angola": "Angola",
    "Alemanha": "Germany",
    "Andorra": "Andorra",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Benin": "Benin",
    "Austria": "Austria",
    "Áustria": "Austria",
    "Austrália": "Australia",
    "Azerbaijão": "Azerbaijan",
    "Bélgica": "Belgium",
    "Bolívia": "Bolivia",
    "Bangladesh": "Bangladesh",
    "Bósnia e Herzegovina": "Bosnia and Herzegovina",
    "Brasil": "Brazil",
    "Bulgária": "Bulgaria",
    "Bolivia": "Bolivia",
    "Canadá": "Canada",
    "Chile": "Chile",
    "China": "China",
    "Catar": "Qatar",
    "Colômbia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Croácia": "Croatia",
    "Cuba": "Cuba",
    "Dinamarca": "Denmark",
    "Equador": "Ecuador",
    "Eslováquia": "Slovakia",
    "Eslovênia": "Slovenia",
    "Espanha": "Spain",
    "Estados Unidos": "United States of America",
    "EUA": "United States of America",
    "Eua": "United States of America",
    "Estônia": "Estonia",
    "Etiópia": "Ethiopia",
    "Finlândia": "Finland",
    "França": "France",
    "Geórgia": "Georgia",
    "Grécia": "Greece",
    "Guatemala": "Guatemala",
    "Guiana": "Guyana",
    "Gana": "Ghana",
    "Honduras": "Honduras",
    'República de Honduras': "Honduras",
    "Hungria": "Hungary",
    "Holanda": "Holland",
    "Haiti": "Haiti",
    "Islândia": "Iceland",
    "Índia": "India",
    "Japão": "Japan",
    "Cabo Verde": "Cape Verde",
    "África do Sul": "South Africa",
    "Ã�frica do Sul": "South Africa",
    "Irlanda": "Ireland",
    "Itália": "Italy",
    "Inglaterra": "United Kingdom",
    "Latvia": "Latvia",
    "Liechtenstein": "Liechtenstein",
    "Lituânia": "Lithuania",
    "Luxemburgo": "Luxembourg",
    "Macedônia": "Macedonia",
    "Malta": "Malta",
    "México": "Mexico",
    "Moldova": "Moldova",
    "Mônaco": "Monaco",
    "Montenegro": "Montenegro",
    "Países Baixos": "Netherlands",
    "Nicarágua": "Nicaragua",
    "Noruega": "Norway",
    "Panamá": "Panama",
    "Paraguai": "Paraguay",
    "Peru": "Peru",
    "Polônia": "Poland",
    "Portugal": "Portugal",
    "Reino Unido": "United Kingdom",
    "República Checa": "Czech Republic",
    "República Tcheca": "Czech Republic",
    "Romênia": "Romania",
    "Rússia": "Russia",
    'Federação Russa': "Russia",
    'Federação da Rússia': "Russia",
    "San Marino": "San Marino",
    "Sérvia": "Serbia",
    "Sérvia e Montenegro": "Serbia and Montenegro",
    "Suécia": "Sweden",
    "Suíça": "Switzerland",
    'Confederação Suíça': "Switzerland",
    "Suriname": "Suriname",
    "Turquia": "Turkey",
    "Ucrânia": "Ukraine",
    "Uruguai": "Uruguay",
    "Venezuela": "Venezuela",
    "Guiné Equatorial": "Eq. Guinea",
    "Nigéria": "Nigeria",
    "Moçambique": "Mozambique",
    "Togo": "Togo",
    "Botsuana": "Botswana",
    "Botsuana) e Johanesburgo (África do Sul": "Botswana;South Africa",
    "Jamaica": "Jamaica",
    "Burcongo": "Burkina Faso;Congo",
    "Chile) e Buenos Aires (Argentina": "Chile;Argentina",
    "Honduras) e  Manágua  (Nicarágua": "Honduras;Nicaragua",
    "El Salvador": "El Salvador",
    "Vietnã": "Vietnam",
    "Indonésia": "Indonesia",
    "Burkina Faso": "Burkina Faso",
    "Timor-Leste": "Timor-Leste",
    'Timor Leste': "Timor-Leste",
    "Salvadorcuba": "El Salvador;Cuba",
    "France Eng": "France;United Kingdom",
    "Trinidad e Tobago": "Trinidad and Tobago",
    "Arábia Saudita": "Saudi Arabia",
    "Cazaquistão": "Kazakhstan",
    "Namíbia": "Namibia",
    "Líbia": "Libya",
    "Salv Guate": "El Salvador;Guatemala",
    "Palestina": "Palestine",
    'Autoridade Nacional Palestina': "Palestine",
    'ANP': "Palestine",
    "Israel": "Israel",
    "Cisjordânia": "West Bank and Gaza",
    "Jordânia": "Jordan",
    "Irã": "Iran",
    "Tanzânia": "Tanzania",
    "Quênia": "Kenya",
    "Coreia do Sul": "South Korea",
    'Coréia do Sul': "South Korea",
    'CoReia do Sul': "South Korea",
    'República da Coréia': "South Korea",
    "Zâmbia": "Zambia",
    "Haitsalv": "Haiti;El Salvador",
    "Uruchil": "Uruguay;Chile",
    "Ispalcisjor": "Israel;Palestine;West Bank and Gaza;Jordan",
    "Arguay": "Argentina;Uruguay",
    "Caboguique Tanzamafr": "Cape Verde;Eq. Guinea;Kenya;Tanzania;Zambia;South Africa",
    "Urupara": "Uruguay;Paraguay",
    "Venelombia": "Venezuela;Colombia",
    "Congo": "Congo",
    "Gabão": "Gabon",
    "República Dominicana": "Dominican Rep.",
    "Saotomeeprincipe": "São Tomé and Príncipe",
    "Camarões": "Cameroon",
    "Senegal": "Senegal",
    "Escócia": "United Kingdom",
    "República Portuguesa": "Portugal",
    "Italia": "Italy",
    "Guiné Bissau": "Guinea-Bissau",
    "Guiné-Bissau": "Guinea-Bissau",
    "Nações Unidas": "United Nations",
    "República Francesa": "France",
    "Costa do Marfim": "Ivory Coast",
    "Líbano": "Lebanon",
    "Vaticano": "Vatican",
    "Hamburgo": "---Hamburgo",
    'Nova Delhi': "---New Dheli",
    'Massachussetts': "---Massachussetts",
    "Lima": "---Lima",
    "Exxon Mobile": capital,
    "Banco Africano de Desenvolvimento": entity,
    "Nova Zelândia": "New Zealand",
    "Banco Interamericano de Desenvolvimento": entity,
    "Conselho de Cooperação do Golfo": entity,
    # "Conferência Consultiva do Povo Chinês" : entity,
    "Fundo Monetário Internacional": entity,
    "Comitê Olímpico Internacional": entity,
    "Siemens": capital,
    "Enel": capital,
    'Citigroup EUA': capital,
    'Citibank-NA EUA': capital,
    'Fórum Econômico  Mundial': 'World Economic Forum',
    'Kuwait': 'Kuwait',
    "Ranbaxy Farmacêutica": capital,
    'Fundação Friedrich Ebert': entity,
    'República Italiana': 'Italy',
    "Foxconn": capital,
    'Huawei': capital,
    "Cingapura": "Singapore",
    "Paris": "---Paris",
    'República da Etiópia': "Ethiopia",
    "Novartis": capital,
    'Bill & Melinda Gates Foundation': entity,
    'State Grid Corporate of China': capital,
    'Ambev': capital,
    "Londres": "---London",
    "Marrocos": "Morocco",
    'Nação Argentina': "Argentina",
    'República Argentina': "Argentina",
    'República da Índia': "India",
    "Santiago": "---Santiago"

}

city_mapping = {
    "Carabogo": "Caracas and Bogota",
    "Bissau": "Bissau",
    "Ciudaguyana": "Ciudad Guyana",
    "Salamanca": "Salamanca",
    "Puerto Maldonado": "Puerto Maldonado",
    "Cidade do Porto": "Porto",
    "Tóquio": "Tokyo",
    "Gleneagles": "Gleneagles",
    "Nagóia": "Nagoya",
    "Dacar": "Dakar",
    "Aquila": "Rome and L'Aquila",
    "Brazzaville": "Brazzaville",
    "Rivasu": "Rivera and Assuncion",
    "Ilhamanadarlujo": "Sal, Malabo, Nairobi, Dar es Salaam, Lusaca, Pretoria and Johannesburg",
    "Buenvideu": "Buenos Aires and Montevideo",
    "Jerberama": "Jerusalem, Bethlehem, Ramallah and Amman",
    "Montiago": "Montevideo and Santiago",
    "Rivera": "Rivera",
    "Mar del Plata": "Mar del Plata",
    "San Juan": "San Juan",
    "Seul": "Seoul",
    "Amã": "Amman",
    "Dar Es Salaam": "Dar es Salaam",
    "Lusaca": "Lusaka",
    "Cancún": "Cancún",
    "Jerusalém": "Jerusalem",
    "Belém": "Bethlehem",
    "Ramalá": "Ramallah",
    "Argel": "Algers",
    "Sirte": "Sirte",
    "Genebra": "Geneva",
    "Chimoré": "Chimoré",
    "Bariloche": "Bariloche",
    "Nova Iorque e Pittsburgh": "New York and Pittsburgh",
    "Pittsburgh": "Pittsburgh",
    "Ecaterimburgo": "Yekaterinburg",
    "Berlim": "Berlin",
    "Isla Margarita": "Isla Margarita",
    "Caracas e El Tigre": "Caracas and El Tigre",
    "El Tigre": "El Tigre",
    "Lisboa e Estoril": "Lisbon and Estoril",
    "Estoril": "Estoril",
    "Kiev": "Kiev",
    "Trípoli": "Tripoli",
    "Istambul": "Istanbul",
    "Astana": "Astana",
    "San Salvador": "San Salvador",
    "São José": "San Jose",
    "Moscou": "Moscow",
    "Oslo": "Oslo",
    "Hamburgo": "Hamburg",
    "Mendoza": "Mendoza",
    "Lisboa": "Lisbon",
    "Pequim": "Beijing",
    "Xiamen": "Xiamen",
    "Córdoba": "Cordoba",
    "Nova York": "New York",
    "Buenos Aires": "Buenos Aires",
    "Zurique": "Zurich",
    "Vinã del Mar": "Viña del Mar",
    "Viña del Mar": "Viña del Mar",
    "Parislondres": "Paris and London",
    "Lima": "Lima",
    "Assunção": "Asuncion",
    'Ilha do Sal': "Sal",
    "Puerto Vallarta": "Puerto Vallarta",
    "Joanesburgo": "Johannesburg",
    "Johanesburgo": "Johannesburg",
    "Johannesburgo": "Johannesburg",
    "Quito": "Quito",
    "Santiago": "Santiago",
    "Nova Iorque": "New York",
    "La Paz": "La Paz",
    "San José": "San Jose",
    "Colônia": "Colonia del Sacramento",
    "Montevidéu": "Montevideo",
    "Cidade do Panamá": "Panama City",
    "Cidade do México": "Mexico City",
    "Bruxelas": "Brussels",
    "Washington": "Washington",
    "São Francisco": "San Francisco",
    "Ufa": "Ufa",
    "Roma e Milão": "Rome and Milan",
    "Roma": "Rome",
    "Milão": "Milan",
    "Bogotá": "Bogota",
    "Estocolmo": "Stockholm",
    "Linköping": "Linköping",
    "Helsinque": "Helsinki ",
    "Antália": "Antalya",
    "Paris": "Paris",
    "Malabo": "Malabo",
    "Abuja": "Abuja",
    "Caracas": "Caracas",
    "Durban": "Durban",
    "Adis Abeba": "Adis Abeba",
    "Paramaribo": "Paramaribo",
    "Petersburgo": "Saint Petersburg",
    "São Petersburgo": "Saint Petersburg",
    "Joanesbugo": "Johannesburg",
    "Davos": "Davos",
    "Província de Artemisa": "Artemisa Province",
    "Havana": "Havana",
    "Valparaiso": "Valparaiso",
    "Doha": "Doha",
    "Brisbane": "Brisbane",
    "Província de Entre Rios": "Entre Rios Province",
    "Porto Príncipe": "Port-au-Prince",
    "Hannover": "Hanover",
    "Nova Délhi": "New Delhi",
    "Nova Delhi": "New Delhi",
    "Boston": "Boston",
    "Cartagena das Índias": "Cartagena ",
    "Los Cabos": "Los Cabos",
    "Londres": "London",
    "Cadiz": "Cadiz",
    "Sevilha": "Seville",
    "Madri": "Madrid",
    "Lisboa e Coimbra": "Lisbon and Coimbra",
    "Sanya": "Sanya",
    "Boao": "Boao",
    "Xian": "Xian",
    "Sófia": "Sofia",
    "Gorna Oryahovitsa": "Gorna Oryahovitsa",
    "Ancara": "Ankara",
    "Pretória": "Pretoria",
    "Maputo": "Maputo",
    "Luanda": "Luanda",
    "Cannes": "Cannes",
    "Pequim, Sanya, Boao e Xian": "Pequim, Sanya, Boao e Xian",
    "Gaborone": "Gaborone and Johannesburg",
    "Puerto Iguazú": "Puerto Iguazú",
    "Viena": "Viena",
    "Ciudad Guayana": "Ciudad Guayana",
    "Cochabamba": "Cochabamba",
    "Valparaíso  e Viña del Mar": "Valparaíso and Viña Del Mar",
    "Georgetown": "Georgetown",
    "Barcelona e Isla Margarita": "Barcelona and Margarita Island",
    "Berlim e Heiligendamm": "Berlin and Heiligendamm",
    "Tegucigalpa": "Tegucigalpa and Managua",
    "Manágua": "Managua",
    "Kingston": "Kingston",
    "Copenhague": "Copenhagen",
    "Ouagabraza": "Ouagadougou and Brazzaville",
    "Ouagadougou": "Ouagadougou",
    "Cidade da Guatemala": "Guatemala City",
    "Haia e Amsterdã": "The Hague and Amsterdam",
    "Praga": "Prague",
    "Acra": "Accra",
    "Portsalv": "Port-au-Prince and San Salvador",
    "São Salvador": "San Salvador",
    "San Miguel de Tucumán": "San Miguel de Tucumán",
    "Sapporo": "Sapporo",
    "Hanói": "Hanoi",
    "Jacarta": "Jakarta",
    "Riberalta": "Riberalta",
    "Letícia": "Leticia",
    "Madri e Toledo": "Madrid and Toledo",
    "Vaticano": "Vatican",
    "Díli": "Dili",
    "Salv Cuba": "San Salvador and Havana",
    "Punta Arenas": "Punta Arenas",
    "Oiapoque": "Oyapock",
    "Arroyo Concepción": "Arroyo Concepción",
    "Maracaibo": "Maracaibo",
    "Washington e Nova Iorque": "Washington and New York",
    "Porto de Espanha": "Port of Spain",
    "Riade": "Riyadh",
    "Salvadorguate": "San Salvador and Guatemala City",
    "Teerã": "Tehran",
    "Nairóbi": "Nairobi",
    "Monterrey": "Monterrey",
    "Pequim e Xangai": "Beijing and Shanghai",
    "Guadalajara": "Guadalajara",
    "Libreville": "Libreville",
    "Cobija": "Cobija",
    "Santo Domingo": "Santo Domingo",
    "Cuzco": "Cuzco",
    "Dehliagramum": "New Deli, Agra and Bombay",
    "Santacsi": "Santa Cruz de la Sierra",
    "Saotome": "São Tomé",
    "Montevidéu  e Paysandú": "Montevideo and Paysandú",
    "Iaundê": "Yaoundé"
}

jamaica_visit_2007_overview = "- Chegada do presidente Luiz Inácio Lula da Silva a Kingston / Jamaica\n" \
                              "- Visita de cortesia ao senhor Kenneth O. Hall, governador-geral da Jamaica\n" \
                              "- Cerimônia de inauguração da Usina de Etanol da Jamaica Broilers Group\n" \
                              "- Encerramento do Fórum de Negócios sobre Etanol, Biodiesel, Cimento, Gipsita, Soja e Alumínio\n" \
                              " - Encontro privado com a senhora Portia Simpson Miller, primeira-ministra da Jamaica\n- Cerimônia de Assinatura de Atos e Declaração à Imprensa\n" \
                              "- Almoço oferecido pela senhora Portia Simpson Miller, primeira-ministra da Jamaica\n" \
                              "- Audiência ao senhor Bruce Golding, líder da oposição no Parlamento\n" \
                              "- Partida do Presidente da República para a Cidade do Panamá / Panamá\n"

months = ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro",
          "novembro", "dezembro"]

cabinet_member = "Cabinet Member"
political_agency_leader = 'Political/Agency Leader'
first_spouse = 'First-spouse'
monarch = 'Monarch'
ceo = 'CEO/Executive'
prime_minister = 'Prime-minister'
president = "President"
religious_leader = "Religious Leader"
regional_official = "Regional Mayor/Governor"
chancellor = "Chancellor"
secretary_general = 'Secretary-general'

posts_mapping = {
    'presidente': president,
    'presidenta': president,
    'primeiro-ministro': prime_minister,
    'primeira-ministra': prime_minister,
    'chanceler': chancellor,
    'presidentes': 'Presidents',
    'vice-presidente': 'Vice-president',
    'vice-presidenta': 'Vice-president',
    'secretário-geral': secretary_general,
    'diretor-geral': political_agency_leader,
    'diretora-geral': political_agency_leader,
    'fundador': political_agency_leader,
    'diretor-executivo': ceo,
    'diretor executivo': ceo,
    'ceo': ceo,
    'rei': monarch,
    'rainha': monarch,
    'emir': monarch,
    monarch: monarch,
    "conselho de direção": ceo,
    'líder religioso': religious_leader,
    'presidente;presidente': 'president;president',
    'first-spouse': first_spouse,
    'presidente da assembléia': political_agency_leader,
    'presidente  da  câmara': political_agency_leader,
    'Ministro': cabinet_member,
    "comandante": cabinet_member,
    'líder da oposição': political_agency_leader,
    "prefeito": regional_official,
    "senadora": political_agency_leader,
    "senador": political_agency_leader,
    "chairman": ceo,
    "congressista": political_agency_leader

}

empty_post = 'UNKNOWN'

royals = ["rei", "príncipe", "rainha", "princesa", "principe", "emir", "xeica"]

generic_businessperson = 'GBP'

triggers = ["encontro", "bilateral", "trilateral", "reuniao", "reunião", "jantar", "almoço", "audiência", "recepção",
            "ceo"]
negative_triggers = ["cerimônia", "encontro empresarial brasil-Argentina, com a presença", "grandes economias",
                     "ampliada", "ampliado", "banquete", "saudaçao", "sessão", "saudação", "homenagem", "assinatura",
                     "futuras", "prêmio", "g-20", "g-8", "g-7", "chefes", "imprensa", "aos", "partida",
                     "painel", "escola-tipo", "visita", "entrevista", "cumprimentos", "chegada", "metalúrgicos",
                     "passeio", "coquetel", "furacões", "encontro empresarial", "abertura", "portinari", "deposição",
                     "chute", "membros", "descerramento", "velório", "posse", "pós-201",
                     "mudança do clima", "seminário", "exéquias"]  # recepção

leaders_mapping = {
    "leader": {"figure": "polished_name", "country": "polished_countryOrInstitution", "posts": []},
    "HC1": {"figure": "Hugo Chavez", "country": "Venezuela", "posts": [president]},
    "JS1": {"figure": "John Sweeney", "country": "--entity", "posts": [political_agency_leader]},
    "BO1": {"figure": "Barack Obama", "country": "United States of America", "posts": [president]},
    "JS2": {"figure": "Jens Stoltenberg", "country": "Norway", "posts": [prime_minister]},
    "NS1": {"figure": "Nicolas Sarkozy", "country": "France", "posts": [president]},
    "REII": {"figure": "Queen Elizabeth II", "country": "United Kingdom", "posts": [monarch]},
    "GB1": {"figure": "Gordon Brown", "country": "United Kingdom", "posts": [prime_minister, cabinet_member]},
    "HJ1": {"figure": "Hu Jintao", "country": "China", "posts": [president]},
    "PM1": {"figure": "Patrick Manning", "country": "Trinidad and Tobago", "posts": [prime_minister]},
    "CK1": {"figure": "Cristina Kirchner", "country": "Argentina", "posts": [president]},
    "AA1": {"figure": "Abdul Rahman al Attiya", "country": entity, "posts": [political_agency_leader]},
    "AB1": {"figure": "Rei Abdullah bin Abdul Aziz Al Saud", "country": "Saudi Arabia", "posts": ["Monarch"]},
    "WJ1": {"figure": "Wen Jiabao", "country": "China", "posts": [prime_minister]},
    "XJ1": {"figure": "Xi Jinping", "country": "China", "posts": ["Vice-president", president]},
    "JQ1": {"figure": "Jia Qinglin", "country": "China", "posts": [political_agency_leader]},
    "RE1": {"figure": "Recep Tayyip Erdogan", "country": "Turkey", "posts": [prime_minister, president]},
    "VY1": {"figure": "Viktor Yushchenko", "country": "Ukraine", "posts": [president]},
    "AG1": {"figure": "Abdullah Gül", "country": "Turkey", "posts": [president]},
    "HG1": {"figure": "Hayrünissa Gül", "country": "Turkey", "posts": [first_spouse]},
    "SA4": {"figure": 'Sare Davutoglu', "country": "Turkey", "posts": [first_spouse]},
    "KT1": {"figure": "Köksal Toptan", "country": "Turkey", "posts": [political_agency_leader]},
    "AA2": {"figure": "Álvaro Arzú", "country": "Guatemala", "posts": [political_agency_leader]},
    "AC1": {'figure': 'Álvaro Colom', 'country': 'Guatemala', 'posts': [president]},
    "OA1": {'figure': 'Oscar Arias', 'country': 'Costa Rica', 'posts': [president]},
    "HT1": {'figure': 'Hamadoun Touré', 'country': 'United Nations', 'posts': [political_agency_leader]},
    "DM1": {'figure': 'Dmitri Medvedev', 'country': 'Russia', 'posts': [president, prime_minister]},
    "NN1": {'figure': 'Nursultan Nazarbayev', 'country': 'Kazakhstan', 'posts': [president]},
    "KM1": {'figure': 'Karim Massimov', 'country': 'Kazakhstan', 'posts': [prime_minister]},
    "JS3": {'figure': 'José Sócrates', 'country': 'Portugal', 'posts': [prime_minister]},
    "JC1": {'figure': 'Jacques Chirac', 'country': 'France', 'posts': [president, 'Ex-president']},
    "FC1": {'figure': 'Felipe Calderón', 'country': 'Mexico', 'posts': [president]},
    "AM1": {'figure': 'Angela Merkel', 'country': 'Germany', 'posts': [prime_minister]},
    "TA1": {'figure': 'Taro Aso', 'country': 'Japan', 'posts': [prime_minister]},
    "GN1": {'figure': 'Giorgio Napolitano', 'country': 'Italy', 'posts': [president]},
    "KR1": {'figure': 'Kevin Rudd', 'country': 'Australia', 'posts': [prime_minister]},
    "FR1": {'figure': 'Fredrik Reinfeldt', 'country': 'Sweden', 'posts': [prime_minister]},
    "FL1": {'figure': 'Fernando Lugo', 'country': 'Paraguay', 'posts': [president]},
    "EM1": {'figure': 'Evo Morales', 'country': 'Bolivia', 'posts': [president]},
    "RT1": {'figure': 'Rex Tillerson', 'country': capital, 'posts': [ceo]},
    "EB1": {'figure': 'Eike Batista', 'country': capital, 'posts': [ceo]},
    "JZ1": {'figure': 'José Luis Zapatero', 'country': 'Spain', 'posts': [president]},
    "DK1": {'figure': 'Donald Kaberuka', 'country': '---entity', 'posts': [political_agency_leader]},
    "JK1": {'figure': 'John Key', 'country': 'New Zealand', 'posts': [prime_minister]},
    "LM1": {'figure': 'Luis Alberto Moreno', 'country': '---entity', 'posts': [political_agency_leader]},
    "GB2": {'figure': 'Gordon Bejnai', 'country': 'Hungary', 'posts': [prime_minister]},
    "BK1": {'figure': 'Ban Ki-moon', 'country': 'United Nations', 'posts': [secretary_general]},
    "MA1": {'figure': 'Mahmoud Ahmadinejad', 'country': 'Iran', 'posts': [president]},
    "PB1": {'figure': 'Paulo Nogueira Batista', 'country': '---entity', 'posts': [political_agency_leader]},
    "JR1": {'figure': 'Jacques Rogge', 'country': '---entity', 'posts': [political_agency_leader]},
    "MII": {'figure': 'Margareth II', 'country': 'Denmark', 'posts': [monarch]},
    "LR1": {'figure': 'Lars Lokke Rasmussen', 'country': 'Denmark', 'posts': [prime_minister]},
    "HR1": {'figure': 'Hermann von Rompuy', 'country': 'Belgium', 'posts': [prime_minister]},
    "DE1": {'figure': 'Armand  de  Decker', 'country': 'Belgium', 'posts': [political_agency_leader]},
    "PD1": {'figure': 'Patrick Dewael', 'country': 'Belgium', 'posts': [political_agency_leader]},
    "AII": {'figure': 'Albert II', 'country': 'Belgium', 'posts': [monarch]},
    "EB2": {'figure': 'Ewa Björling', 'country': 'Sweden', 'posts': [cabinet_member]},
    "CG1": {'figure': 'Carl Gustaf', 'country': 'Sweden', 'posts': [monarch]},
    "SI1": {'figure': 'Queen Silvia', 'country': 'Sweden', 'posts': [monarch]},
    "FF1": {'figure': 'Franklin Feder', 'country': capital, 'posts': [ceo]},
    "JE1": {'figure': 'Jean-Max Bellerive', 'country': 'Haiti', 'posts': [prime_minister]},
    "MD1": {'figure': "Massimo D'Alema", 'country': 'Italy', 'posts': [prime_minister, 'Ex-Prime-minister']},
    "JB1": {'figure': 'José Manuel Durão Barroso', 'country': 'European Commission',
            'posts': [political_agency_leader, ceo]},
    "SB1": {'figure': 'Silvio Berlusconi', 'country': 'Italy', 'posts': [prime_minister]},
    "AS1": {'figure': 'Aníbal Cavaco Silva', 'country': 'Portugal', 'posts': [president]},
    "HK1": {'figure': 'Horst Köhler', 'country': 'Germany', 'posts': [president]},
    "FS1": {'figure': 'Frank-Walter Steinmeier', 'country': 'Germany', 'posts': [political_agency_leader]},
    "AF1": {'figure': 'Anke Fuchs', 'country': '--entity', 'posts': [political_agency_leader]},
    "MS1": {'figure': 'Michael Sommer', 'country': '--entity', 'posts': [political_agency_leader]},
    "PL1": {'figure': 'Peter Löscher', 'country': '---capital', 'posts': [ceo]},
    "HA1": {'figure': 'Hans-Christoph Atzpodien', 'country': '--entity', 'posts': [ceo]},
    "OB1": {'figure': 'Ole von Beust', 'country': '---Hamburgo', 'posts': [political_agency_leader]},
    "AG2": {'figure': 'Alan García', 'country': 'Peru', 'posts': [president]},
    "LL1": {'figure': 'Luis Castañeda Lossio', 'country': '---Lima', 'posts': [political_agency_leader]},
    "OH1": {'figure': 'Ollanta Humala', 'country': 'Peru', 'posts': [political_agency_leader, president]},
    "RV1": {'figure': 'Ronald Venetiaan', 'country': 'Suriname', 'posts': [president]},
    "MA2": {'figure': 'Mahmoud Abbas', 'country': 'Palestine', 'posts': [president]},
    "MZ1": {'figure': 'Meles Zenawi', 'country': 'Ethiopia', 'posts': [prime_minister]},
    "RC1": {'figure': 'Raul Castro', 'country': 'Cuba', 'posts': ['Vice-president', president]},
    "p1": {'figure': 'Person One', 'country': 'SomeCountry', 'posts': [president]},
    "p2": {'figure': 'Person Two', 'country': 'SomeCountry', 'posts': [first_spouse]},
    "RA1": {'figure': 'Ricardo Alarcón', 'country': 'Cuba', 'posts': [political_agency_leader]},
    "JB2": {'figure': 'Jan Peter Balkenende', 'country': 'Netherlands', 'posts': [prime_minister]},
    "RB1": {'figure': 'Queen Beatrix', 'country': 'Netherlands', 'posts': [monarch]},
    "VK1": {'figure': 'Václav Klaus', 'country': 'Czech Republic', 'posts': [president]},
    "JK2": {'figure': 'John Agyekum Kufour', 'country': 'Ghana', 'posts': [president]},
    "TH1": {'figure': 'Tarja Halonen', 'country': 'Finland', 'posts': [president]},
    "DO1": {'figure': 'Donald Tusk', 'country': 'Poland', 'posts': [prime_minister, political_agency_leader]},
    "ND1": {'figure': 'Nicanor Duarte', 'country': 'Paraguay', 'posts': [president]},
    "BG1": {'figure': 'Bruce Golding', 'country': 'Jamaica', 'posts': [prime_minister]},
    "FF2": {'figure': 'Franco Frattini', 'country': 'Italy', 'posts': ['Chancellor', cabinet_member]},
    "MT1": {'figure': 'Mirek Topolanek', 'country': 'Czech Republic', 'posts': [prime_minister]},
    "GP1": {'figure': 'Georgi Parvanov', 'country': 'Bulgaria', 'posts': [president]},
    "JR2": {'figure': 'José Manuel Zelaya Rosales', 'country': 'Honduras', 'posts': [president]},
    "RP1": {'figure': 'René Préval', 'country': 'Haiti', 'posts': [president]},
    "ES1": {'figure': 'Elias Antonio Saca', 'country': 'El Salvador', 'posts': [president]},
    "LM2": {'figure': 'Lee Myung-bak', 'country': 'South Korea', 'posts': [president]},
    "GB3": {'figure': 'George W. Bush', 'country': 'United States of America', 'posts': [president]},
    "SH1": {'figure': 'Stephen Harper', 'country': 'Canada', 'posts': [prime_minister]},
    "YF1": {'figure': 'Yasuo Fukuda', 'country': 'Japan', 'posts': [prime_minister]},
    "NT1": {'figure': 'Nguyen Minh Triet', 'country': 'Vietnam', 'posts': [president]},
    "NT2": {'figure': 'Nguyen Phu Trong', 'country': 'Vietnam', 'posts': [political_agency_leader]},
    "ND2": {'figure': 'Nguyen Tan Dung', 'country': 'Vietnam', 'posts': [prime_minister]},
    "NM1": {'figure': 'Nong Duch Manh', 'country': 'Vietnam', 'posts': [political_agency_leader]},
    "JR3": {'figure': 'José Ramos-Horta', 'country': 'Timor-Leste', 'posts': [president]},
    "SY1": {'figure': 'Susilo Bambang Yudhoyono', 'country': 'Indonesia', 'posts': [president]},
    "AV1": {'figure': 'Álvaro Uribe Vélez', 'country': 'Colombia', 'posts': [president]},
    "AL1": {'figure': 'Alan García Pérez', 'country': 'Peru', 'posts': [president]},
    "WU1": {'figure': 'Wu Bangguo', 'country': 'China', 'posts': [political_agency_leader]},
    "SH2": {'figure': 'Shimon Peres', 'country': 'Israel', 'posts': [president]},
    "HI1": {'figure': 'Hifikepunye Pohamba', 'country': 'Namibia', 'posts': [president]},
    "LA1": {'figure': 'Laurent Gbagbo', 'country': 'Ivory Coast', 'posts': [president]},
    "MI1": {'figure': 'Michel Suleiman', 'country': 'Lebanon', 'posts': [president]},
    "JA1": {'figure': 'Jakata Kikwete', 'country': 'Tanzania', 'posts': [president]},
    "AN1": {'figure': 'Anders Fogh Rasmussen', 'country': 'Denmark', 'posts': [prime_minister]},
    "JU1": {'figure': 'Juan Carlos', 'country': 'Spain', 'posts': [monarch]},
    "JO1": {'figure': 'José Maria Barreda', 'country': 'Spain', 'posts': [political_agency_leader]},
    "KG1": {'figure': 'Kgalema Motlanthe', 'country': 'South Africa', 'posts': [president]},
    "MA3": {'figure': 'Manmohan Singh', 'country': 'India', 'posts': [prime_minister]},
    "AR1": {'figure': 'Armando Guebuza', 'country': 'Mozambique', 'posts': [president]},
    "GI1": {'figure': 'Gianfranco Fini', 'country': 'Italy', 'posts': [political_agency_leader]},
    "LU1": {'figure': 'Luca Cordero di Montezemolo', 'country': capital, 'posts': [ceo]},
    "PI1": {'figure': 'Piero Gnudi', 'country': capital, 'posts': [ceo]},
    "GI2": {'figure': 'Giuliano Poletti', 'country': capital, 'posts': [ceo]},
    "GA1": {'figure': 'Gabriele Galatere di Genola', 'country': capital, 'posts': [ceo]},
    "PA1": {'figure': 'Pope Benedict XVI', 'country': 'Vatican', 'posts': [political_agency_leader]},
    "RI1": {'figure': 'Richard Clark', 'country': capital, 'posts': [ceo]},
    "PE1": {'figure': 'Peter Loescher', 'country': capital, 'posts': [ceo]},
    "HE1": {'figure': 'Hector Ruiz', 'country': capital, 'posts': [ceo]},
    generic_businessperson: {'figure': 'Business Person', 'country': capital, 'posts': [ceo]},
    "KL1": {'figure': 'Klaus Schwab', 'country': 'World Economic Forum', 'posts': [political_agency_leader]},
    "TO1": {'figure': 'Tony Blair', 'country': 'United Kingdom', 'posts': [prime_minister]},
    "TA2": {'figure': 'Tabaré Vázquez', 'country': 'Uruguay', 'posts': [president]},
    "NE1": {'figure': 'Néstor Kirchner', 'country': 'Argentina', 'posts': [president]},
    "NI1": {'figure': 'Nicanor Duarte Frutos', 'country': 'Paraguay', 'posts': [president]},
    "PA2": {'figure': 'Pranab Mukherjee', 'country': 'India', 'posts': ['Cabinet Member']},
    "AU1": {'figure': 'Auul Pakir Jainulabdeen Abdul Kalam', 'country': 'India', 'posts': [president]},
    "SO1": {'figure': 'Sonia Gandhi', 'country': 'India', 'posts': [political_agency_leader]},
    "JO2": {'figure': 'José Vicente de Sá Pimentel', 'country': 'Brazil', 'posts': [cabinet_member]},
    "ER1": {'figure': 'Ernst Kerbusch', 'country': "Friedrich Ebert Foundation", 'posts': [political_agency_leader]},
    "LO1": {'figure': 'Lothar Bisky', 'country': "---Linkspartei", 'posts': [political_agency_leader]},
    "FR2": {'figure': 'Franz Müntefering', 'country': 'Germany', 'posts': [cabinet_member, "Vice-Chancellor"]},
    "RO1": {'figure': 'Romano Prodi', 'country': 'Italy', 'posts': [prime_minister]},
    "MI2": {'figure': 'Michele Bachelet', 'country': 'Chile', 'posts': [president]},
    "HA2": {'figure': 'Hans-Gert Pötering', 'country': 'European Parliament', 'posts': [political_agency_leader]},
    "ZE1": {'figure': 'José Manuel Zelaya Rosales', 'country': 'Honduras', 'posts': [president]},
    "DA1": {'figure': 'Daniel Ortega Saavedra', 'country': 'Nicaragua', 'posts': [president]},
    "RO2": {'figure': 'Rosario Murillo', 'country': 'Nicaragua', 'posts': [first_spouse]},
    "MA4": {'figure': 'Martín Torrijos', 'country': 'Panama', 'posts': [president]},
    "MA5": {'figure': 'Matti Vanhanen', 'country': 'Finland', 'posts': [prime_minister]},
    "SA1": {'figure': 'Sauli Niinistö', 'country': 'Finland', 'posts': [political_agency_leader]},
    "GO1": {'figure': 'Göran Persson', 'country': 'Sweden', 'posts': ['Ex-Prime-minister']},
    "HA3": {'figure': 'Hans Jensen', 'country': 'Denmark', 'posts': [political_agency_leader]},
    "LE1": {'figure': 'Lech Kaczynski', 'country': 'Poland', 'posts': [president]},
    "HA4": {'figure': 'Han Duck-soo', 'country': 'South Korea', 'posts': [prime_minister]},
    "SU1": {'figure': 'Susilo Yudhoyono', 'country': 'Indonesia', 'posts': [president]},
    "BL1": {'figure': 'Blaise Compaoré', 'country': 'Burkina Faso', 'posts': [president]},
    "JO3": {'figure': 'José Eduardo dos Santos', 'country': 'Angola', 'posts': [president]},
    "MI3": {'figure': 'Micheline Calmy-Rey', 'country': 'Switzerland', 'posts': [president]},
    "CA1": {'figure': 'Carlos Lage', 'country': 'Cuba', 'posts': ['Vice-president']},
    "FR3": {'figure': 'François Fillon', 'country': 'France', 'posts': [prime_minister]},
    "FI1": {'figure': 'Fidel Castro', 'country': 'Cuba', 'posts': [cabinet_member]},
    "MA6": {'figure': 'Maurício Funes', 'country': 'El Salvador', 'posts': [president]},
    "VA1": {'figure': 'Vanda Pignato', 'country': 'El Salvador', 'posts': [first_spouse]},
    "RE2": {'figure': 'Reuven Rivlin', 'country': 'Israel', 'posts': [political_agency_leader]},
    "BE1": {'figure': 'Benjamin Netanyahu', 'country': 'Israel', 'posts': [prime_minister]},
    "SA2": {'figure': 'Salam Fayaad', 'country': 'Palestine', 'posts': [prime_minister]},
    "RA2": {'figure': 'King Abdullah II', 'country': 'Jordan', 'posts': [monarch]},
    "RA3": {'figure': 'Queen Rania', 'country': 'Jordan', 'posts': [monarch]},
    "PR1": {'figure': 'Prince Hassan ibn Talal', 'country': 'Jordan', 'posts': [monarch]},
    "SA3": {'figure': 'Samir Rifai', 'country': 'Jordan', 'posts': [prime_minister]},
    "YU1": {'figure': 'Yukio Hatoyama', 'country': 'Japan', 'posts': [prime_minister]},
    "VL1": {'figure': 'Vladimir Putin', 'country': 'Russia', 'posts': [prime_minister, president]},
    "HA5": {'figure': 'Hamad bin Khalifa Al Thani', 'country': 'Qatar', 'posts': [monarch]},
    "AI1": {'figure': 'Aiatolá Ali Khamenei', 'country': 'Iran', 'posts': [political_agency_leader, religious_leader]},
    "AL2": {'figure': 'Ali Larijani', 'country': 'Iran', 'posts': [political_agency_leader]},
    "JO4": {'figure': 'José Brito', 'country': 'Cape Verde', 'posts': [prime_minister]},
    "MW1": {'figure': 'Mwai Kibaki', 'country': 'Kenya', 'posts': [president]},
    "RU1": {'figure': 'Rupiah Bwezani Banda', 'country': 'Zambia', 'posts': [president]},
    "JA3": {'figure': 'Jacob Zuma', 'country': 'South Africa', 'posts': [president]},
    "TZ1": {'figure': 'Tzipi Livni', 'country': 'Israel', 'posts': [political_agency_leader]},
    "JO5": {'figure': 'José Mujica', 'country': 'Uruguay', 'posts': [president]},
    "LU2": {'figure': 'Lucia Topolansky', 'country': 'Uruguay', 'posts': [political_agency_leader]},
    "PE2": {'figure': 'Pedro Pires', 'country': 'Cape Verde', 'posts': [president]},
    "OB2": {'figure': 'Obiang Nguema Mbasogo', 'country': 'Eq. Guinea', 'posts': [president]},
    "LK1": {'figure': 'L.K. Advani', 'country': 'India', 'posts': [political_agency_leader]},
    "RE3": {'figure': 'Ren Zhengfei', 'country': capital, 'posts': [ceo]},
    "TE1": {'figure': 'Terry Gou', 'country': capital, 'posts': [ceo]},
    "SE1": {'figure': 'Sebastián Piñera', 'country': 'Chile', 'posts': [president]},
    "DA2": {'figure': 'David Cameron', 'country': 'United Kingdom', 'posts': [political_agency_leader, prime_minister]},
    "JU2": {'figure': 'Juan Manuel Santos', 'country': 'Colombia', 'posts': [president]},
    "YV1": {'figure': 'Yves Leterme', 'country': 'Belgium', 'posts': [prime_minister]},
    "HE2": {'figure': 'Herman Van Rompuy', 'country': 'European Council', 'posts': [political_agency_leader]},
    "BO2": {'figure': 'Boyko Borissov', 'country': 'Bulgaria', 'posts': [prime_minister]},
    "JU3": {'figure': 'Julia Gillard', 'country': 'Australia', 'posts': [prime_minister]},
    "LE2": {'figure': 'Lee Hsien Loong', 'country': 'Singapore', 'posts': [prime_minister]},
    "PO1": {'figure': 'Porfírio Lobo', 'country': 'Honduras', 'posts': [president]},
    "MI4": {'figure': 'Michel Martelly', 'country': 'Haiti', 'posts': [president]},
    "ST1": {'figure': 'Stefan Zoller', 'country': "---Federation of German Industries",
            'posts': [political_agency_leader]},
    "SU2": {'figure': 'Susan Hockfield', 'country': '---MIT', 'posts': [political_agency_leader]},
    "DE2": {'figure': 'Deval Patrick', 'country': '---Massachussetts', 'posts': [political_agency_leader]},
    "DR1": {'figure': 'Drew Faust', 'country': '---Harvard', 'posts': [political_agency_leader]},
    "MA7": {'figure': 'Mario Monti', 'country': 'Italy', 'posts': [prime_minister]},
    "MA8": {'figure': 'Mariano Rajoy', 'country': 'Spain', 'posts': [president]},
    "JO6": {'figure': 'Joseph Blatter', 'country': '---FIFA', 'posts': [political_agency_leader]},
    "SO2": {'figure': 'Queen Sofia', 'country': 'Spain', 'posts': [monarch]},
    "FR4": {'figure': 'François Hollande', 'country': 'France', 'posts': [president]},
    "BE2": {'figure': 'Bertrand Delanoe', 'country': '---Paris', 'posts': [regional_official]},
    "JE2": {'figure': 'Jean-Pierre Bel', 'country': 'France', 'posts': [political_agency_leader]},
    "EN1": {'figure': 'Enrique Peña Nieto', 'country': 'Mexico', 'posts': [president]},
    "GO2": {'figure': 'Goodluck Ebele Jonathan', 'country': 'Nigeria', 'posts': [president]},
    "PA3": {'figure': 'Pope Francis', 'country': 'Vatican', 'posts': [political_agency_leader, religious_leader]},
    "HA6": {'figure': 'Hailemariam Desalegn', 'country': 'Ethiopia', 'posts': [prime_minister]},
    "AN2": {'figure': 'António José Seguro', 'country': 'Portugal', 'posts': [political_agency_leader]},
    "MA9": {'figure': 'Mário Soares', 'country': 'Portugal', 'posts': ["Ex-president"]},
    "BI1": {'figure': 'Bill Clinton', 'country': 'United States of America', 'posts': ["Ex-president"]},
    "PA4": {'figure': 'Paulo Passos Coelho', 'country': 'Portugal', 'posts': [prime_minister]},
    "HO1": {'figure': 'Horácio Cartes', 'country': 'Paraguay', 'posts': [president]},
    "AH1": {'figure': 'Ahmet Davutoglu', 'country': 'Turkey', 'posts': [prime_minister]},
    "TO2": {'figure': 'Tony Abbott', 'country': 'Australia', 'posts': [prime_minister]},
    "EM2": {'figure': 'Sheikh Tamim bin Hamad Al Thani', 'country': 'Qatar', 'posts': [monarch]},
    "XE1": {'figure': 'Sheikha Moza bint Nasser Al-Missned', 'country': 'Qatar', 'posts': [monarch]},
    "JU4": {'figure': 'Juan Carlos Varela', 'country': 'Panama', 'posts': [president]},
    "MA10": {'figure': 'Mark Zuckerberg', 'country': capital, 'posts': [ceo]},
    "JO7": {'figure': 'Joseph Biden', 'country': 'United States of America', 'posts': ['Vice-president']},
    "JA4": {'figure': 'Janet Napolitano', 'country': '---University of California', 'posts': [political_agency_leader]},
    "BI2": {'figure': 'Bill Jeffrey', 'country': '---SRI International', 'posts': [political_agency_leader]},
    "AL3": {'figure': 'Alexander Lukashenko', 'country': 'Belarus', 'posts': [president]},
    "SE2": {'figure': 'Sergio Mattarella', 'country': 'Italy', 'posts': [president]},
    "JO8": {'figure': 'José Graziano', 'country': '---FAO', 'posts': [political_agency_leader]},
    "MA11": {'figure': 'Matteo Renzi', 'country': 'Italy', 'posts': [prime_minister]},
    "HA7": {'figure': 'Hassan Rohani', 'country': 'Iran', 'posts': [president]},
    "ST2": {'figure': 'Stefan Löfven', 'country': 'Sweden', 'posts': [prime_minister]},
    "ER2": {'figure': 'Erna Solberg', 'country': 'Norway', 'posts': [prime_minister]},
    "JE3": {'figure': 'Jean-Claude Junker', 'country': 'European Commission', 'posts': [political_agency_leader]},
    "JU5": {'figure': 'Juan Somavía', 'country': '---International Labour Organization',
            'posts': [political_agency_leader]},
    "HE3": {'figure': 'Henry Kissinger', 'country': 'United States of America', 'posts': [political_agency_leader]},
    "CO1": {'figure': 'Condoleezza Rice', 'country': 'United States of America', 'posts': [political_agency_leader]},
    "MA12": {'figure': 'Madeleine Albright', 'country': 'United States of America', 'posts': [political_agency_leader]},
    "RU2": {'figure': 'Rupert Murdoch', 'country': capital, 'posts': [ceo]},
    "NA1": {'figure': 'Narendra Modi', 'country': 'India', 'posts': [prime_minister]},
    "BI3": {'figure': 'Bill Gates', 'country': capital, 'posts': [ceo]},
    "ME1": {'figure': 'Melinda Gates', 'country': capital, 'posts': [ceo]},
    "ER3": {'figure': 'Erick Schmidt', 'country': capital, 'posts': [ceo]},
    "JA5": {'figure': 'Jacques Diouf', 'country': '---FAO', 'posts': [political_agency_leader]},
    "RA4": {'figure': 'Rafael Correa', 'country': 'Ecuador', 'posts': [president]},
    "HE4": {'figure': 'Henrique Cueto', 'country': capital, 'posts': [ceo]},
    "GO3": {'figure': 'Gonzalo García Balmaceda', 'country': capital, 'posts': [ceo]},
    "MA13": {'figure': 'Marcelo Rebelo de Sousa', 'country': 'Portugal', 'posts': [president]},
    "DE3": {'figure': 'Vyacheslav Volodin', 'country': 'Russia', 'posts': [political_agency_leader]},
    "VA2": {'figure': 'Valentina Matvienko', 'country': 'Russia', 'posts': [political_agency_leader]},
    "OL1": {'figure': 'Olemic Thommessen', 'country': 'Norway', 'posts': [president]},
    "RE4": {'figure': 'King Harald V', 'country': 'Norway', 'posts': [monarch]},
    "SH3": {'figure': 'Shu Yinbiao', 'country': capital, 'posts': [ceo]},
    "SU3": {'figure': 'Sun Yafang', 'country': capital, 'posts': [ceo]},
    "YU2": {'figure': 'Yu Zhengsheng', 'country': 'China', 'posts': [political_agency_leader]},
    "LI1": {'figure': 'Li Keqiang', 'country': 'China', 'posts': [prime_minister]},
    "DO2": {'figure': 'Donald Trump', 'country': 'United States of America', 'posts': [president]},
    "AN3": {'figure': 'António Guterres', 'country': 'United Nations', 'posts': [secretary_general]},
    "AB2": {'figure': 'Abdel Fattah El-Sisi', 'country': 'Egypt', 'posts': [president]},
    "DA3": {'figure': 'David Granger', 'country': 'Guyana', 'posts': [president]},
    "AN4": {'figure': 'Ángel Gurria', 'country': 'OCDE', 'posts': [secretary_general]},
    "JO9": {'figure': 'João Lourenço', 'country': 'Angola', 'posts': [president]},
    "SA5": {'figure': 'Saad Hariri', 'country': 'Lebanon', 'posts': [prime_minister]},
    "TH2": {'figure': 'Thomas J. Donohue', 'country': 'Chamber of Commerce of the United States',
            'posts': [political_agency_leader]},
    "JU6": {'figure': 'Juan Orlando Hernández Alvarado', 'country': 'Honduras', 'posts': [president]},
    "PA5": {'figure': 'Paul Cook', 'country': 'United States of America', 'posts': [political_agency_leader]},
    "JO10": {'figure': 'Jorge Carlos Fonseca', 'country': 'Cape Verde', 'posts': [president]},
    "CY1": {'figure': 'Cyril Ramaphosa', 'country': 'South Africa', 'posts': [president]},
    "AB3": {'figure': 'Abdelkader Bensalah', 'country': 'Algeria', 'posts': [political_agency_leader]},
    "AM2": {'figure': 'Amar Saadani', 'country': 'Algeria', 'posts': [political_agency_leader]},
    "AH2": {'figure': 'Ahmed Ouyahia', 'country': 'Algeria', 'posts': [cabinet_member]},
    "MA14": {'figure': 'Mathieu Kerekou', 'country': 'Benin', 'posts': [president]},
    "HE5": {'figure': 'Helen Clark', 'country': 'New Zealand', 'posts': [prime_minister]},
    "DR2": {'figure': 'Driss Jetou', 'country': 'Morocco', 'posts': [prime_minister]},
    "FE1": {'figure': 'Festus Mogae', 'country': 'Botswana', 'posts': [president]},
    "KE1": {'figure': 'Ken Livingstone', 'country': '---London', 'posts': [regional_official]},
    "AL4": {'figure': 'Alejandro Toledo', 'country': 'Peru', 'posts': [president]},
    "HE6": {'figure': 'Heinz Fischer', 'country': 'Austria', 'posts': [president]},
    "VI1": {'figure': 'Vicente Fox', 'country': 'Mexico', 'posts': [president]},
    "MA15": {'figure': 'Manuel Zelaya', 'country': 'Honduras', 'posts': [president]},
    "FA1": {'figure': 'Faure Gnassingbé', 'country': 'Togo', 'posts': [president]},
    "JO11": {'figure': 'John Agyekum Kufuor', 'country': 'Ghana', 'posts': [president]},
    "AR2": {'figure': 'Armando Emílio Guebuza', 'country': 'Mozambique', 'posts': [president]},
    "AB4": {'figure': 'Abdelaziz Bouteflika', 'country': 'Algeria', 'posts': [president]},
    "GE1": {'figure': 'Gerhard Schroeder', 'country': 'Germany', 'posts': [prime_minister]},
    "SA6": {'figure': 'Samuel Schmid', 'country': 'Switzerland', 'posts': [president]},
    "KJ1": {'figure': 'Kjell Magne Bondevik', 'country': 'Norway', 'posts': [prime_minister]},
    "TH3": {'figure': 'Thabo Mbeki', 'country': 'South Africa', 'posts': [president]},
    "BH1": {'figure': 'Bharrat Jagdeo', 'country': 'Guyana', 'posts': [president]},
    "RO4": {'figure': 'Robert Corbin', 'country': 'Guyana', 'posts': [political_agency_leader]},
    "RU3": {'figure': 'Runaldo Venetiaan', 'country': 'Suriname', 'posts': [president]},
    "PA6": {'figure': 'Paul Biya', 'country': 'Cameroon', 'posts': [president]},
    "OL2": {'figure': 'Olusegun Obasanjo', 'country': 'Nigeria', 'posts': [president]},
    "MO1": {'figure': 'Mohamed Ibn Chambas', 'country': 'Economic Community of West African States',
            'posts': [secretary_general]},
    "HE7": {'figure': 'Henrique Rosa', 'country': 'Guinea-Bissau', 'posts': [president]},
    "CA2": {'figure': 'Carlos Gomes Júnior', 'country': 'Guinea-Bissau', 'posts': [prime_minister]},
    "FR5": {'figure': 'Francisco Benante', 'country': 'Guinea-Bissau', 'posts': [political_agency_leader]},
    "RO5": {'figure': 'Roh Moo-Hyun', 'country': 'South Korea', 'posts': [president]},
    "KO1": {'figure': 'Koizumi', 'country': 'Japan', 'posts': [prime_minister]},
    "JO12": {'figure': 'Jorge Sampaio', 'country': 'Portugal', 'posts': [president]},
    "DO3": {'figure': 'Dominique de Villepin', 'country': 'France', 'posts': [prime_minister]},
    "OS1": {'figure': 'Oscar Berger', 'country': 'Guatemala', 'posts': [president]},
    "KO2": {'figure': 'Kofi Annan', 'country': 'United Nations', 'posts': [secretary_general]},
    "AB5": {'figure': 'Abel Pacheco', 'country': 'Costa Rica', 'posts': [president]},
    "LY1": {'figure': 'Lyudmila Putin', 'country': 'Russia', 'posts': ["First-spouse"]},
    "AL5": {'figure': 'Alfredo Palacio', 'country': 'Ecuador', 'posts': [president]},
    "PA7": {'figure': 'Paul Martin', 'country': 'Canada', 'posts': [prime_minister]},
    "AT1": {'figure': 'Atal Bihari Vajpayee', 'country': 'India', 'posts': [prime_minister]},
    "AB6": {'figure': 'Abdul Kalan', 'country': 'India', 'posts': [president]},
    "RI2": {'figure': 'Ricardo Lagos', 'country': 'Chile', 'posts': [president]},
    "SE3": {'figure': 'Seyed Mohammed Khatami', 'country': 'Iran', 'posts': [president]},

    "LE3": {'figure': 'Leonid Kutchma', 'country': 'Ukraine', 'posts': [president]},
    "JA6": {'figure': 'James Wolfensohn', 'country': 'World Bank', 'posts': [political_agency_leader]},
    "BE3": {'figure': 'Benjamin Mkapa', 'country': 'Tanzania', 'posts': [president]},
    "CA3": {'figure': 'Carlos Mesa', 'country': 'Bolivia', 'posts': [president]},
    "AL6": {'figure': 'Aleksander Kwasniewski', 'country': 'Poland', 'posts': [president]},
    "JO13": {'figure': 'John Snow', 'country': 'United States of America', 'posts': [cabinet_member]},
    "JU7": {'figure': 'Juan Somavia', 'country': 'International Labour Organization',
            'posts': [political_agency_leader]},
    "OM1": {'figure': 'Omar Bongo Ondimba', 'country': 'Gabon', 'posts': [president]},
    "PE3": {'figure': 'Pedro Verona Rodrigues Pires', 'country': 'Gabon', 'posts': [president]},
    "AG3": {'figure': 'Agostinho Lopes', 'country': 'Gabon', 'posts': [political_agency_leader]},
    "JO14": {'figure': 'José Maria Neves', 'country': 'Cape Verde', 'posts': [prime_minister]},
    "AB7": {'figure': 'Abel Pacheco de la Espriella', 'country': 'Costa Rica', 'posts': [president]},
    "MA16": {'figure': 'Marcos Libedinsky', 'country': 'Chile', 'posts': ["Supreme Court Justice"]},
    "JO15": {'figure': 'Joaquín Lavín', 'country': '---Santiago', 'posts': ['Regional Mayor/Governor']},
    "AR3": {'figure': 'Arturo Martínez', 'country': 'Chile', 'posts': [political_agency_leader]},
    "LU3": {'figure': 'Lucio Gutierrez', 'country': 'Ecuador', 'posts': [president]},
    "JE4": {'figure': 'Jean Ping', 'country': 'Gabon', 'posts': [chancellor]},
    "BE4": {'figure': 'Begum Khaleda Zia', 'country': 'Bangladesh', 'posts': [prime_minister]},
    "JA7": {'figure': 'Jay Aseelan Naidoo', 'country': 'Southern Africa Development Bank', 'posts': [political_agency_leader]},
    "BO3" : {'figure': 'Boniface Alexandre', 'country': 'Haiti', 'posts': [president]},
    "AB8" : {'figure': 'Abdoulaye Wade', 'country': 'Senegal', 'posts': [president]},
    "LE4" : {'figure': 'Lee Soo-Hoo', 'country': 'South Korea', 'posts': [political_agency_leader]},
    "BE5" : {'figure': 'Bertrand Delanoë', 'country': '---Paris', 'posts': [regional_official]}

}

leaders_mapping_codes = {
    'Boniface Alexandre' : 'BO3' ,
    'Lee Soo-Hoo' : 'LE4' ,
    'Abdoulaye Wade' : 'AB8' ,
    'Bertrand Delanoë' : 'BE5' ,
    'Jay Aseelan Naidoo': 'JA7',
    'Marcos Libedinsky': 'MA16',
    'Sr. Hans Joachim Nikolin': generic_businessperson,
    'José Maria Neves': 'JO14',
    'Begum Khaleda Zia': 'BE4',
    'Arturo Martínez': 'AR3',
    'Lucio Gutierrez': 'LU3',
    'Jean Ping': 'JE4',
    'Senhor Ricardo Lagos': "RI2",
    'Joaquín Lavín': 'JO15',
    'Abel Pacheco de la Espriella': 'AB7',
    'Atal Bihari Vajpayee': 'AT1',
    'Omar Bongo Ondimba': 'OM1',
    'Aleksander Kwasniewski': 'AL6',
    'John Snow': 'JO13',
    'Agostinho Lopes': 'AG3',
    'Carlos Mesa': 'CA3',
    'Rodrigues Pires': None,
    "Pedro  Verona": "PE3",
    'Ricardo Lagos': 'RI2',
    'Benjamin Mkapa': "BE3",
    'Juan Somavia': 'JU7',
    'Leonid Kutchma': 'LE3',
    'James Wolfensohn': 'JA6',
    'Abdul Kalan': 'AB6',
    'Seyed Mohammed Khatami': 'SE3',
    'Pascoale Pistorio': generic_businessperson,
    'Francisco Benante': 'FR5',
    'Paul Martin': 'PA7',
    'Tabaré Vásquez': 'TA2',
    'Kofi Annan': 'KO2',
    'Lyudmila Putin': 'LY1',
    'Abel Pacheco': 'AB5',
    'Alfredo Palacio': 'AL5',
    'Oscar Berger': 'OS1',
    'Dominique de Villepin': 'DO3',
    'Jorge Sampaio': 'JO12',
    'Carlos Gomes Júnior': 'CA2',
    'Koizumi': 'KO1',
    'Roh Moo-Hyun': 'RO5',
    'Mohamed Ibn Chambas': 'MO1',
    'Henrique Rosa': 'HE7',
    'Runaldo Venetiaan': 'RU3',
    'Olusegun Obasanjo': 'OL2',
    'Paul Biya': 'PA6',
    'Thabo Mbeki': 'TH3',
    'Bharrat Jagdeo': 'BH1',
    'Senhor Kjell Magne Bondevik': 'KJ1',
    'Gerhard Schroeder': "GE1",
    'Gerhard Schröder': 'GE1',
    'Robert Corbin': 'RO4',
    'Samuel Schmid': 'SA6',
    'Itamar Franco': None,
    'John Agyekum Kufuor': 'JO11',
    'Senhor Klaus Schwab': 'KL1',
    'Suas Majestades o Rei Carlos XVI Gustavo': 'CG1',
    'Armando Emílio Guebuza': 'AR2',
    'Abdelaziz Bouteflika': 'AB4',
    'Faure Gnassingbé': 'FA1',
    'Heinz Fischer': 'HE6',
    'Vicente Fox': 'VI1',
    'Vicente Fox Quesada': "VI1",
    'Helen Clark': "HE5",
    'Festus Mogae': 'FE1',
    'Manuel Zelaya': 'MA15',
    'Alejandro Toledo': 'AL4',
    'Driss Jetou': "DR2",
    'Ken Livingstone': 'KE1',
    'Mathieu Kerekou': 'MA14',
    'Ahmed Ouyahia': 'AH2',
    'Amar Saadani': "AM2",
    'Abdelkader Bensalah': 'AB3',
    'Hassan Houhani': 'HA7',
    'Presidente de Cabo Verde': "JO10",
    "Senhor Andrew Liveris": generic_businessperson,
    'Cyril Ramaphosa': 'CY1',
    'Paul Cook': 'PA5',
    'Senhor Ángel Gurria': 'AN4',
    'Juan Orlando Hernández Alvarado': 'JU6',
    'Thomas J. Donohue': 'TH2',
    'Senhor Dave MacLennan': generic_businessperson,
    'Senhor Ben Van Beurden': generic_businessperson,
    'Senhor Lakshmi Mittal': generic_businessperson,
    'Senhor Saad Hariri': 'SA5',
    'Donald Trump': 'DO2',
    'Senhor João Lourenço': 'JO9',
    'Senhor José Manuel Durão Barroso': "JB1",
    'Senhor Francesco Starace': generic_businessperson,
    'Abdel Fattah El-Sisi': 'AB2',
    'David Granger': 'DA3',
    'António Guterres': 'AN3',
    'Li Keqiang': 'LI1',
    'Senhor Carlos Brito': generic_businessperson,
    'Yu Zhengsheng': 'YU2',
    'Senhor James Quincey': generic_businessperson,
    'Chen Feng': generic_businessperson,
    'Lu Shun': generic_businessperson,
    'Sun Yafang': 'SU3',
    'Shu Yinbiao': 'SH3',
    'Rei Harald V da Noruega': 'RE4',
    'Valentina Matvienko': "VA2",
    'Dmitry Medvedev': "DM1",
    'Marcelo Rebelo de Sousa': 'MA13',
    'Olemic Thommessen': 'OL1',
    'Deputado Vyacheslav Volodin': 'DE3',
    'Gonzalo García Balmaceda': 'GO3',
    'Rafael Correa': 'RA4',
    'Henrique Cueto': 'HE4',
    'Erick Schmidt': 'ER3',
    'Jacques Diouf': 'JA5',
    'Bill Gates': "BI3",
    'Melinda Gates': "ME1",
    'Narendra Modri': 'NA1',
    'Madeleine Albright': 'MA12',
    'Rupert Murdoch': "RU2",
    'Condoleezza Rice': "CO1",
    'Henry Kissinger': "HE3",
    'Juan Somavía': 'JU5',
    'Erna Solberg': "ER2",
    'Sare Davutoglu': "SA4",
    'Jean-Claude Junker': 'JE3',
    'Hassan Rohani': 'HA7',
    'Stefan Löfven': 'ST2',
    'Matteo Renzi': 'MA11',
    'José Graziano': 'JO8',
    'Joseph Biden': 'JO7',
    'Sergio Mattarella': 'SE2',
    'Alexander Lukashenko': 'AL3',
    'Janet Napolitano': 'JA4',
    'Bill Jeffrey': 'BI2',
    'Xeica Mozah': 'XE1',
    'Senadora Lucia Topolansky': "LU2",
    'Juan Carlos Varela': 'JU4',
    'Juan Manoel Santos': 'JU2',
    'Mark Zuckerberg': 'MA10',
    'Nasser': None,
    'Tony Abbott': 'TO2',
    'Emir do Catar  Xeque Tamin bin': "EM2",
    'Bill Clinton': "BI1",
    'Ahmet Davutoglu': 'AH1',
    'Cesar Alierta': generic_businessperson,
    'Horácio Cartes': 'HO1',
    'Mário Soares': "MA9",
    'Hailemariam Desalegn': 'HA6',
    'António José Seguro': 'AN2',
    'Bertrand Delanoe': 'BE2',
    'Paulo Passos Coelho': 'PA4',
    'Goodluck Ebele Jonathan': 'GO2',
    'Enrique Peña Nieto': 'EN1',
    'Jean-Pierre Bel': 'JE2',
    'Rainha Sofia da Espanha': "SO2",
    'François Hollande': 'FR4',
    'Rainha Elisabeth II': "REII",
    'Mario Monti': 'MA1',
    'Joseph Blatter': 'JO6',
    'Mariano Rajoy': 'MA8',
    'Drew Faust - Presidenta da Universidade de Harvad': 'DR1',
    'Deval Patrick': "DE2",
    'Susan Hockfield': 'SU2',
    'Stefan Zoller': "ST1",
    'Lee Hsien Loong': 'LE2',
    'Lee Hsien': 'LE2',
    'Michel Martelly': 'MI4',
    'Porfírio Lobo': 'PO1',
    'Boyko Borissov': 'BO2',
    'Julia Gillard': 'JU3',
    'Herman Van Rompuy': "HE2",
    'Sebastián Piñera': 'SE1',
    'David Cameron': 'DA2',
    'Yves Leterme': 'YV1',
    'Juan Manuel Santos': 'JU2',
    'Ren Zhengfei': 'RE3',
    'Terry Gou': 'TE1',
    'L.K. Advani': 'LK1',
    'Tzipi Livni': 'TZ1',
    'Obiang Nguema Mbasogo': 'OB2',
    'Pedro Pires': 'PE2',
    'José Mujica': "JO5",
    'Jakaya Mrisho Kikwete': 'JA1',
    'Rupiah Bwezani Banda': 'RU1',
    'Jacob Zuma': 'JA3',
    'Mwai Kibaki': 'MW1',
    'José Brito': "JO4",
    'Recep Tayyip Erdogan': "RE1",
    'Recep Erdogan': "RE1",
    'Hamad bin Khalifa Al Thani': "HA5",
    'Ali Larijani': "AL2",
    'Aiatolá Ali Khamenei': "AI1",
    'Vladimir Putin': 'VL1',
    'Yukio Hatoyama': 'YU1',
    'Samir Rifai': "SA3",
    'Príncipe Hassan ibn Talal': 'PR1',
    'Fidel Castro': 'FI1',
    'Rei Abdullah II': 'RA2',
    "Rainha Rania": 'RA3',
    'Salam Fayaad': 'SA2',
    'Reuven Rivlin': "RE2",
    'Benjamin Netanyahu': 'BE1',
    'Vanda Pignato': "VA1",
    'Maurício Funes': 'MA6',
    'Jean-Max Bellerive': 'JE1',
    'François Fillon': 'FR3',
    'Álvaro Uribe': 'AV1',
    'Carlos Lage': 'CA1',
    'Micheline Calmy-Rey': 'MI3',
    'José Eduardo dos Santos': 'JO3',
    'Blaise Compaoré': 'BL1',
    'Susilo Yudhoyono': 'SU1',
    'Lech Kaczynski': 'LE1',
    'Han Duck-soo': 'HA4',
    'Hans Jensen': 'HA3',
    'Göran Persson': 'GO1',
    'Sauli Niinistö': 'SA1',
    'Matti Vanhanen': 'MA5',
    'Martín Torrijos': 'MA4',
    'Rosario Murillo': "RO2",
    'Rosário Murillo': "RO2",
    'Daniel  Ortega  Saavedra': 'DA1',
    'Daniel Ortega Saavedra': 'DA1',
    'Daniel Ortega': 'DA1',
    'Zelaya Rosales': 'ZE1',
    'Hans-Gert Pötering': 'HA2',
    'Romano Prodi': 'RO1',
    'Nicanor Duarte Frutos': 'NI1',
    "Franz Müntefering": "FR2",
    "Lothar Bisky": "LO1",
    "Ernst Kerbusch": "ER1",
    'Karl-Ulrich Köhler': generic_businessperson,
    "Hubertus Troska": generic_businessperson,
    "José Vicente de Sá Pimentel": "JO2",
    "Sonia Gandhi": "SO1",
    "Pranab Mukherjee": 'PA2',
    "Malvinder Mohan Singh": generic_businessperson,
    "D. J. Ramesh": generic_businessperson,
    'M. Thiagarajan': generic_businessperson,
    "Auul Pakir Jainulabdeen Abdul Kalam": "AU1",
    "Nicanor Duarte Fructos": "NI1",
    "Néstor Kirchner": "NE1",
    'Nestor Kirchner': 'NE1',
    "Tabaré Vázquez": "TA2",
    'Tony Blair': 'TO1',
    "Neville Isdell": generic_businessperson,
    'Tarek Sultan Al': generic_businessperson,
    'Klaus Schwab': 'KL1',
    'Chuck Prince': generic_businessperson,
    'William Rhodes': generic_businessperson,
    "Eric Schmidt": generic_businessperson,
    'Hector Ruiz': 'HE1',
    'Richard Clark': 'RI1',
    'Peter Loescher': 'PE1',
    'Papa Bento XVI': 'PA1',
    'Papa Francisco': 'PA3',
    'Audiência com Sua Santidade o Papa Francisco': "PA3",
    'Gabriele Galatere di Genola': 'GA1',
    'Giuliano Poletti': 'GI2',
    'Piero Gnudi': 'PI1',
    'Luca Cordero di Montezemolo': 'LU1',
    'Gianfranco Fini': 'GI1',
    'Armando Guebuza': 'AR1',
    'Manmohan Singh': 'MA3',
    'Kgalema Motlanthe': 'KG1',
    'Anders Fogh Rasmussen': 'AN1',
    'José Maria Barreda': 'JO1',
    'Jakata Kikwete': 'JA1',
    'Wu Bangguo': 'WU1',
    'Michel Suleiman': 'MI1',
    'Laurent Gbagbo': 'LA1',
    'Hifikepunye Pohamba': 'HI1',
    'Shimon Peres': 'SH2',
    'Álvaro Uribe Vélez': 'AV1',
    'Susilo Bambang Yudhoyono': 'SY1',
    'José Ramos-Horta': 'JR3',
    'Nong Duch Manh': 'NM1',
    'Nguyen Tan Dung': 'ND2',
    'Nguyen Minh Triet': 'NT1',
    'Nguyen Phu Trong': 'NT2',
    'Lee Myung-bak': 'LM2',
    'Yasuo Fukuda': 'YF1',
    'Stephen Harper': 'SH1',
    'George W. Bush': 'GB3',
    'Elias Antonio Saca': 'ES1',
    'René Préval': 'RP1',
    'José Manuel  Zelaya Rosales': 'JR2',
    'Georgi Parvanov': 'GP1',
    'Hugo Chávez': 'HC1',
    'Hugo Chávez Paysandú': "HC1",
    'Hugo Cháves Frias': 'HC1',
    "Hugo Chávez Frias": "HC1",
    'John Sweeney': 'JS1',
    'Barack Obama': 'BO1',
    'Michelle Bachelet': 'MI2',
    'Michele Bachelet': 'MI2',
    'Jens Stoltenberg': 'JS2',
    'Nicolas Sarkozy': 'NS1',
    'Nicholas Sarkozy': 'NS1',
    'Rainha Elizabeth II': 'REII',
    'Gordon Brown': 'GB1',
    'Hu Jintao': 'HJ1',
    'Patrick Manning': 'PM1',
    'Cristina Kirchner': 'CK1',
    'Abdul Rahman al Attiya': 'AA1',
    'Rei Abdullah bin Abdul Aziz Al Saud': 'AB1',
    'Wen Jiabao': 'WJ1',
    'Xi Jinping': 'XJ1',
    'Senhor Xi Jinping': "XJ1",
    'Jia Qinglin': 'JQ1',
    'Senhor Narendra Modi': "NA1",
    'Recep Tayyip': 'RE1',
    'Recep Tayyip  ': 'RE1',
    'Viktor Yushchenko': 'VY1',
    'Abdullah Gül': 'AG1',
    'Hayrünissa Gül': 'HG1',
    'Köksal Toptan': 'KT1',
    'Álvaro Arzú': 'AA2',
    'Álvaro Colom': 'AC1',
    'Óscar Arias': 'OA1',
    'Hamadoun Touré': 'HT1',
    'Dmitri Medvedev': 'DM1',
    'Nursultan Nazarbayev': 'NN1',
    'Karim Massimov': 'KM1',
    'José Sócrates': 'JS3',
    'Jacques Chirac': 'JC1',
    'Sr. Jacques Chirac': "JC1",
    'Ex-Presidente': None,
    'Rei da Suécia': None,
    'Felipe Calderón': 'FC1',
    'Angela Merkel': 'AM1',
    'Ângela Merkel': 'AM1',
    'Taro Aso': 'TA1',
    'Giorgio Napolitano': 'GN1',
    'Kevin Rudd': 'KR1',
    'Fredrik Reinfeldt': 'FR1',
    'Fernando Lugo': 'FL1',
    'Evo Morales': 'EM1',
    'Rex Tillerson': 'RT1',
    'Eike Batista': 'EB1',
    'José Luis Zapatero': 'JZ1',
    'José Luís Zapatero': 'JZ1',
    'Jorge Luís Rodriguez Zapatero': "JZ1",
    'José Luiz Rodriguez Zapatero': "JZ1",
    'José Luis Rodríguez Zapatero': 'JZ1',
    'Juan Carlos I': 'JU1',
    'Rei Juan Carlos I da Espanha': "JU1",
    'Rei Juan Carlos I': "JU1",
    'José Luiz Rodríguez Zapatero Toledo': 'JZ1',
    "José Luiz Rodríguez Zapatero": "JZ1",
    'Donald Kaberuka': 'DK1',
    'John Key': 'JK1',
    'Luis Alberto Moreno': 'LM1',
    'Gordon Bejnai': 'GB2',
    'Ban Ki-moon': 'BK1',
    'Ban Ki-Moon': "BK1",
    'Mahmoud Ahmadinejad': 'MA1',
    'Paulo Nogueira Batista': 'PB1',
    'Jacques Rogge': 'JR1',
    'Margarete II': 'MII',
    'Lars Lokke Rasmussen': 'LR1',
    'Hermann von Rompuy': 'HR1',
    'Decker': 'DE1',
    'Patrick Dewael': 'PD1',
    'Alberto II': 'AII',
    'Rei Alberto II': 'AII',
    'Ewa Björling': 'EB2',
    'Carl Gustaf': 'CG1',
    'Rainha Silvia': 'SI1',
    'Rainha Sílvia': "SI1",
    'Franklin Feder': 'FF1',
    "Massimo D'Alema": 'MD1',
    'José Manuel Durão Barroso': 'JB1',
    'Durão Barroso': 'JB1',
    'Silvio Berlusconi': 'SB1',
    'Aníbal Cavaco Silva': 'AS1',
    'Cavaco Silva': "AS1",
    'Horst Köhler': 'HK1',
    'Angela Merkel Chancelaria Federal': 'AM1',
    'Frank-Walter Steinmeier': 'FS1',
    'Anke Fuchs': 'AF1',
    'Michael Sommer': 'MS1',
    'Peter Löscher': 'PL1',
    'Hans-Christoph Atzpodien': 'HA1',
    'Ole von Beust': 'OB1',
    'Alan García': 'AG2',
    'Luis Castañeda Lossio': 'LL1',
    'Ollanta Humala': 'OH1',
    'Ronald Venetiaan': 'RV1',
    'Mahmoud Abbas': 'MA2',
    'Mahmud Abbas': 'MA2',
    'Meles Zenawi': 'MZ1',
    'Raúl Castro': 'RC1',
    'Ricardo Alarcón': 'RA1',
    'Cristina Fernández': 'CK1',
    'Kirchner': None,
    'Person One': 'p1',
    'Person Two': 'p2',
    'Jan Peter Balkenende': 'JB2',
    'Rainha Beatrix': 'RB1',
    'Václav Klaus': 'VK1',
    'Luiz Inácio Lula da Silva': None,
    'Luiz Inácio Lula  da Silva': None,
    'Dilma Rousseff': None,
    'John Agyekum Kufour': 'JK2',
    'Tarja Halonen': 'TH1',
    'Donald Tusk': 'DO1',
    'Nicanor Duarte': 'ND1',
    'Bruce Golding': 'BG1',
    'Franco Frattini': 'FF2',
    'Mirek Topolanek': 'MT1',
    'Alan García Peru': 'AL1',
    'Alan García Pérez Pérez': None,
    'Rei da Espanha': None,
    'Juan Carlos': 'JU1',
    'Hakan Buskhe': generic_businessperson,
    'Carlos Brito': generic_businessperson,
    'Thomas Montag': generic_businessperson,
    'Joseph Jimenez': generic_businessperson,
    'Paul Polman': generic_businessperson

}

separator_char = ';'

account_post_inconsistency = {
    "2003": [],
    "2004": ['GBP', 'JA6', 'RO1', 'GE1', 'JO13', 'MA16', 'AR3', 'GO1', 'JE4', 'JA7', 'JC1', 'RI2', 'JZ1', 'KO2'],
    "2005": ['JB1', 'GE1', 'MO1','LE4', 'JU1', 'LM1', 'LY1', 'AV1', 'HC1', 'JZ1'],
    "2006": ['AB3', 'GB1', "AM1"],
    "2007": ['RI1', 'PE1', 'HE1', 'GBP', 'GB1', 'KL1', 'SO1', 'JO2', 'ER1', 'LO1', 'FR2', 'HA2', 'RO2', 'SA1', 'GO1',
             'HA3', 'LM1', "AM1"],
    "2008": ['CK1', 'EM1', 'JB1', 'NM1', 'AV1', 'AL1', 'JR1', 'AN1', 'JU1', 'JZ1', 'JO1', 'RC1', 'LU1', 'PI1', 'GA1',
             'GI2', 'PA1'],
    "2009": ['JS1', 'AA1', 'JQ1', 'HG1', 'KT1', 'AA2', 'HT1', 'JC1', 'RT1', 'EB1', 'DK1', 'LM1', 'PB1',
             'JR1', 'DE1', 'PD1', 'EB2', 'FR1', 'CG1', 'SI1', 'FF1', 'MD1', 'JB1', 'FS1', 'AF1', 'MS1',
             'PL1', 'HA1', 'OB1', 'LL1', 'OH1', "AM1"],
    "2010": ['JE1', 'VA1', 'RE2', 'SA2', 'RA3', 'HA5', 'AI1'],
    "2011": ['RE3', 'TE1', 'WU1', 'HE2', 'JB1', 'AM1'],
    "2012": ['ST1', 'SU2', 'DE2', 'DR1', 'JO6', 'JB1', 'SO2', 'JE2', 'DM1', "AM1"],
    "2013": ['GN1', 'PA3', 'AN2', 'MA9', 'BI1', 'GBP', "AM1"],
    "2014": ['GBP', 'HE2', 'JB1', "AM1"],
    "2015": ['MA10', 'RU2', 'HE3', 'MA12', 'JA4', 'ER3', 'CO1', 'BI2', 'BI3', 'ME1', 'SI1', 'SA4', 'JE3', 'DO1'],
    "2016": ['GO3'],
    "2017": ['MA9', 'DE3', 'SH3', 'SU3', 'GBP', 'YU2', 'KL1'],
    "2018": ['GBP', 'TH2']

}
